config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :image_posts
  resources :text_posts
  resources :posts
  devise_for :users
  resources :users
  get 'home/index'

  authenticated :user do
  	root 'posts#index', as: "authenticated_root"
  end

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/image_post.rb
class ImagePost < Post
  validates :url, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :user_id, presence: true
  validates :type, presence: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :leader, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/text_post.rb
class TextPost < Post
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :subscriptions, foreign_key: :follower_id, dependent: :destroy
  has_many :leaders, through: :subscriptions

  has_many :reverse_subscriptions, foreign_key: :leader_id, class_name: 'Subscription', dependent: :destroy
  has_many :followers, through: :reverse_subscriptions

  has_many :posts, dependent: :destroy
  has_many :text_posts, dependent: :destroy
  has_many :image_posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def following?(leader)
    leaders.include? leader
  end

  def follow!(leader)
    if leader != self && !following?(leader)
      leaders << leader
    end
  end

  def timeline_user_ids
    leader_ids + [id]
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
    end

    def current_user!
      redirect_to new_user_session_path unless current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :current_user!

  def create
    @comment = current_user.comments.build(comment_params)
      if @comment.save
        redirect_to post_path(@comment.post_id), notice: 'Comment was successfully added.'
      else
        redirect_to post_path(@comment.post_id), alert: 'Error creating comment.'
      end
  end

private
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController
  def show
  end

  def edit
    @image_post = current_user.image_posts.find(params[:id])
  end

  def update
    @image_post = current_user.image_posts.find(params[:id])
      if @image_post.update(image_post_params)
        redirect_to post_path(@image_post), notice: "Post updated!"
      else
        redirect_to edit_image_post_path, notice: "Error updating post."
      end
  end

  def image_post_params
    params.require(:image_post).permit(:title, :url, :user_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :current_user!

  # GET /posts
  # GET /posts.json
  def index
    user_ids = current_user.timeline_user_ids
    @post = Post.where(user_id: user_ids).order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @can_moderate = (current_user == @post.user)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :url, :type, :user_id)
    end
end

app/controllers/text_posts_controller.rb
class TextPostsController < ApplicationController
  def show
  end

  def edit
    @text_post = current_user.text_posts.find(params[:id])
  end

  def update
    @text_post = current_user.text_posts.find(params[:id])
      if @text_post.update(text_post_params)
        redirect_to post_path(@text_post), notice: "Post updated!"
      else
        redirect_to edit_text_post_path, notice: "Error updating post."
      end
  end

  def text_post_params
    params.require(:text_post).permit(:title, :body, :type, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
      flash.clear
    end
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/image_posts_helper.rb
module ImagePostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/text_posts_helper.rb
module TextPostsHelper
end

app/views/comments/_comment.html.erb
<p><%=time_ago_in_words(comment.created_at) %> ago <%= comment.user.name %> said: </p>
  <blockquote>
    <%= comment.body %>

  <% if @can_moderate %>
    <p><%= link_to 'Destroy', comment_path(comment), method: :delete, data: {confirm: "Are you sure you want to delete this comment?" }, class: "btn btn-default" %></p>
  <% end %>
  </blockquote>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/image_posts/_form.html.erb
<%= simple_form_for(@image_post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/image_posts/_image_post.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= image_post.title %>
    </h3>
  </div>

  <div class="panel-body">
    <%= link_to time_ago_in_words(image_post.created_at), post_path(image_post) %>
    <p><em>By <%= image_post.user.name %></em></p>

    <%= image_tag image_post.url, class: "img-responsive" %>

    <%= image_post.body %>
<br/>
<br/>
    <% if image_post.user == current_user %>
      <p><%= link_to 'Edit', edit_image_post_path(image_post), class: "btn btn-default" %></p>
    <% end %>
  </div>
</div>

app/views/image_posts/edit.html.erb
<div class="page-header">
  <h1>Edit Text Post</h1>
</div>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tumbleclone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Tumble", root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">

                <% if current_user %>
                    <li><%= link_to 'Posts', posts_path %></li>
                    <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                    <li><%= link_to 'Register', new_user_registration_path %>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
  <%= flash_messages %>

  <%= yield %>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :url %>
    <%= f.input :type %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="page-header">
  <h1>Recent Posts</h1>
</div>

<%= render @post %>
<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="page-header">
  <h1><%= @post.title %></h1>
</div>

<%= render @post %>

<h3>Comments<h3>
<%= render @post.comments.order("created_at DESC") %>
<h4>New Comment</h4>
  <%= simple_form_for @post.comments.build do |f| %>
    <div class="form-inputs">
      <%= f.input :body, class: "form-control" %>
    </div>
    <%= f.hidden_field :post_id %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
<br/>
<%= link_to "Home", posts_path, class: "btn btn-default" %>

app/views/text_posts/_form.html.erb
<%= simple_form_for(@text_post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/text_posts/_text_post.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= text_post.title %>
    </h3>
  </div>

  <div class="panel-body">
    <%= link_to time_ago_in_words(text_post.created_at), post_path(text_post) %>
    <p><em>By <%= text_post.user.name %></em></p>
    <%= text_post.body %>
<br/>
<br/>
    <% if text_post.user == current_user %>
      <p><%= link_to 'Edit', edit_text_post_path(text_post), class: "btn btn-default" %></p>
    <% end %>
  </div>

<br/>


</div>

app/views/text_posts/edit.html.erb
<div class="page-header">
  <h1>Edit Text Post</h1>
</div>

<%= render 'form' %>